//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yore_v1.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;

    public partial class Post : IEnumerable<Post>
    {
        public int PostID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Likes { get; set; }

        List<Post> mylist = new List<Post>();

        public IEnumerator<Post> GetEnumerator()
        {
            return ((IEnumerable<Post>)mylist).GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return ((IEnumerable<Post>)mylist).GetEnumerator();
        }
    }
}
